apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
  repoURL: https://grafana.github.io/helm-charts
  targetRevision: 9.0.0
  chart: grafana
  helm:
    values: |-
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      persistence:
        enabled: true
        type: pvc
        volumeName: gitea-pv
        accessModes:
          - ReadWriteOnce
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
        path: /
        pathType: Prefix
        hosts:
          - grafana.lab.pl
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPU: "500"
      grafana.ini:
        auth.ldap:
          active_sync_enabled: true
          enabled: true
        smtp:
          enabled: true
          host: smtp.gmail.com:587
          from_name: Grafana Alerts
      smtp:
        existingSecret: grafana-smtp
        userKey: user
        passwordKey: password
      ldap:
        enabled: true
        config: |-
          [[servers]]
          host = "10.0.0.103"
          port = 389
          use_ssl = false
          start_tls = false
          ssl_skip_verify = true
          bind_dn = "cn=admin,dc=pl,dc=lab"
          bind_password = "Kr0pk@1234"
          search_filter = "(uid=%s)"
          search_base_dns = ["dc=pl,dc=lab"]

          [servers.attributes]
          name = "cn"
          username = "uid"
          member_of = "memberUid"
          email =  "mail"

          [[servers.group_mappings]]
          group_dn = "cn=grafana-admin,dc=pl,dc=lab"
          org_role = "Admin"
          grafana_admin = true
          
          [[servers.group_mappings]]
          group_dn = "*"
          org_role = "Viewer"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
