apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.0
    chart: promtail
    helm:
      values: |-
        config:
          # publish data to loki
          clients:
          - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
            tenant_id: 1
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
